[package]
name = "integrated_product_messages_utilities"
version = "0.1.0"
authors = ["Renan Florez <renan@cloudwalk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
